### ISSUE TITLE
如何在分割时增加颜色种类

### ISSUE THREAD

**Issue by zzhmx** [yatengLG/PSAT#3]
选择分割只有那么集中颜色，如何自己设置其他颜色呢

**Comment by yatengLG** [comment]
设置里添加类别时，不是可以指定颜色嘛0.0

**Comment by zzhmx** [comment]
我的意思是可以指定的颜色种类只有五种，但是如果我的类别比较多怎么办呢

**Comment by yatengLG** [comment]
类别可以自己随便添加啊，填100种都可以；颜色完全自定义...

哪里只有五种T.T

![gnome-shell-screenshot-VPR3M2](https://github.com/yatengLG/PSAT/assets/31759824/5093c9cc-1e2b-45b1-aa13-23bbabd09e89)

![gnome-shell-screenshot-5YD4M2](https://github.com/yatengLG/PSAT/assets/31759824/52cd9b7c-f7f4-4184-8703-2b7b8c96e14a)

**Comment by zzhmx** [comment]
![image](https://github.com/yatengLG/PSAT/assets/58509426/feb83782-078c-4718-be60-3a08ff647920)
w我这为啥没有那个功能？

**Comment by yatengLG** [comment]
点个star告诉你 （斜眼笑）

**Comment by yatengLG** [comment]
菜单栏 第一个下拉，设置里面


可以先看使用步骤
https://github.com/yatengLG/PSAT?tab=readme-ov-file#%E4%BD%BF%E7%94%A8

**Comment by zzhmx** [comment]
哈哈哈哈哈哈哈，多谢，点了
